services:
  - type: web
    name: naruto-quiz-bot
    runtime: python
    plan: free
    autoDeployTrigger: commit

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      python main.py

    healthCheckPath: /healthz

    envVars:
      - key: BOT_DISABLED
        value: false

      - key: PYTHON_VERSION
        value: 3.11.9

      - key: TOKEN
        sync: false

      - key: GUILD_ID
        sync: false

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_KEY
        sync: false

      - key: QUIZ_CHANNEL_NAME
        value: quiz-naruto

      - key: QUIZ_DURATION_SECONDS
        value: "600"

      - key: QUESTIONS_FILE
        value: pytania.json

      - key: LOG_LEVEL
        value: INFO
